### ISSUE TITLE
Improve code coverage for `flash.core.data.utilities.paths`

### ISSUE THREAD

**Issue by JustinGoheen** [Lightning-Universe/lightning-flash#1391]
## Tests/CI

Add tests for `flash.core.data.utilities.paths`

### Motivation

Improve code coverage for the mentioned module

### Pitch

Adding tests for the specific module is a mechanism to familiarize with the code base, to continue to familiarize with the PR process, team conventions in the core code base, and testing best practices.

### Alternatives

None.

### Additional context

Issue was discussed with Ethan at: https://github.com/Lightning-AI/lightning-flash/pull/1386#discussion_r921206003

**Comment by JustinGoheen** [comment]
@krshrimali  I'll be submitting a new draft PR soon; I had to update the branch name and that deleted my previous draft PR.

**Comment by krshrimali** [comment]
@JustinGoheen - Any reason this was closed? :)

**Comment by JustinGoheen** [comment]
I haven't received any feedback for several days now and cannot keep contributions open that appear to be stale

**Comment by krshrimali** [comment]
> I haven't received any feedback for several days now and cannot keep contributions open that appear to be stale

Hi, @JustinGoheen - I appreciate it that you took the time to look at the issue, and create a PR, however - I believe it was communicated well that the PR will be reviewed starting this week, and it is still on my radar for the week. Even if not, I wouldn't call it stale, or close the PR, however - it is totally fine to remove your assignment.

> Edit: Also, in case there are any major changes, and if you are occupied, I'll be happy to update this PR to help land this PR. :))

Also, note that my comment did mention that I'll take care of any edits that need to be done in order to land the PR. So yeah, feel free to leave that to me. Thank you again for your contribution, and I will appreciate your understanding of the delay in the reviews. ❤️

**Comment by Borda** [comment]
> I haven't received any feedback for several days now and cannot keep contributions open that appear to be stale

Flash has is set not for 2 months, so no worries :)
https://github.com/Lightning-AI/lightning-flash/blob/36442115224b013343a2845b232f3ce3eca4c916/.github/stale.yml#L4
